changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: "### {{.Kind}}"
changeFormat: "- {{.Body}}"
kinds:
  - label: Added
    key: added
    auto: minor
  - label: Changed
    key: changed
    auto: minor
  - label: Fixed
    key: fixed
    auto: patch
  - label: Security
    key: security
    auto: patch
  - label: Internal
    key: internal
    auto: patch

newlines:
  beforeChangelogVersion: 1
  afterKind: 1
  beforeKind: 1
  endOfVersion: 1

replacements:
  - path: VERSION
    find: ".*"
    replace: "{{.VersionNoPrefix}}"

envPrefix: CHANGIE_
