---
name: headscale

services:
  server:
    build:
      context: ..

    depends_on:
      minio:
        condition: service_healthy

    environment:
      - HEADSCALE_SERVER_URL=https://hs.example.local
      - HEADSCALE_BASE_DOMAIN=tn.luislavena.local
      # - HEADSCALE_PRIVATE_KEY=CHANGEME
      # - HEADSCALE_NOISE_PRIVATE_KEY=CHANGEME
      - S3_ACCESS_KEY_ID=admin
      - S3_SECRET_ACCESS_KEY=changeme
      - S3_REGION=home
      - S3_BUCKET_NAME=homelab
      - S3_ENDPOINT=http://minio:9000

    labels:
      # Ref: https://docs.orbstack.dev/docker/domains#custom
      - dev.orbstack.domains=hs.example.local
      # Ref: https://docs.orbstack.dev/docker/domains#ports
      - dev.orbstack.http-port=8080

    ports:
      - "8080:8080"

    volumes:
      - headscale:/data

  minio:
    image: registry.docker.com/bitnamilegacy/minio:latest
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=changeme
      - MINIO_DEFAULT_BUCKETS=homelab
      - MINIO_SCHEME=http
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "9001:9001"

    volumes:
      - minio:/bitnami/minio/data

volumes:
  headscale:
    driver: local
  minio:
    driver: local
